### ISSUE TITLE
SDK download window should resize properly

### ISSUE THREAD

**Issue by sarahcodes100** [DeerajTheepshi/processing-android#16] opened 2019-06-24 16:12 UTC
If the user wants to resize the window to see the default installation path, the window should resize properly instead of being fixed to the upper right hand corner like this:
<img width="753" alt="resize" src="https://user-images.githubusercontent.com/494323/60029942-14254080-9670-11e9-9e87-61fce501a721.png">

**Comment by DeerajTheepshi** [comment] 2019-06-25 04:17
@sarahlensing , the intended behavior is to lock the size and prevent the user from resizing. 

Fixed using : 6e1dd0df387a710082e26f1644ca71a7810529fd. Close this if you feel ok, @sarahlensing

**Comment by sarahcodes100** [comment] 2019-06-27 00:39
I see, I think thats fine to lock the size but we should update the path label to resize its text so its clear where the current installation path is without having to click the "change" button. Or show the ending part of the path instead of the beginning?

**Comment by DeerajTheepshi** [comment] 2019-06-27 01:31
We considered this, and added tooltip on the label to let the users know about the complete path.

**Closed as completed** 2019-07-09 01:16 UTC
