### ISSUE TITLE
Detect missing SDK when folder removed manually

### ISSUE THREAD

**Issue by sarahcodes100** [DeerajTheepshi/processing-android#19] opened 2019-06-24 16:31 UTC
If I download the SDK and then manually delete it from disk, when I go back into the Android mode, we should re-prompt so the SDK is downloaded

**Comment by kfrajer** [comment] 2019-06-25 00:24
This is exactly what happens if you delete the Android SDK folder. @sarahlensing  this did not work on Mac OS? I believe I tested this case and it worked on Win OS: the PDE prompted to download the Android SDK as it detected an invalid content in the initial folder defined in the `preferences.txt` file.

**Comment by DeerajTheepshi** [comment] 2019-06-25 04:13
I think this what @sarahlensing could have encountered : (@kfrajer)
- Go into Android Mode .
- Open File explorer and delete the SDK folder from disk .
- Shift to java mode.
- Shift back to android mode.
- **Prompt is not shown**

## Comment : 
I guess this is the intended behavior of PDE. Once a mode is loaded, it is not loaded again. The user has to close the existing PDE and restart the PDE for the new changes to take effect.

**Comment by sarahcodes100** [comment] 2019-06-27 00:37
@DeerajTheepshi @kfrajer Yes, that is exactly what I encountered. 

I was imagining we add a check when the Android mode is enabled that would be on top of the preferences. So `if preferences.sdkdir == null || !sdkdir.exists() show dialog`.

**Comment by DeerajTheepshi** [comment] 2019-06-27 05:33
We already are doing this part . https://github.com/DeerajTheepshi/processing-android/blob/d3803800cd9a6c150bac21bddd814927fef8df23/mode/src/processing/mode/android/AndroidSDK.java#L99

However , I have added a fix which reloads the SDK object everytime checkSDK() is called.

So new work flow is this :
- User damages the SDK folder in some way. (Deleted from disk, renamed a folder, moved it to somewhere etc.)
- User shifts to android mode.
- He's greeted with a message that informs him about a broken SDK path (along with reason) and hence takes him back to installer window with 2 buttons. 
- Based on the reason , the user can either fix his path and locate his path manually / if he deleted the SDK folder completely from disk, he can download a new copy of SDK using the download automatically option. 

Tested, and fixed with 2afe1325cdcc8d2640ce297d3b727f8ed0657e0c.

If you think the changes are fine, you can close the issue. @sarahlensing

**Closed as completed** 2019-07-09 01:17 UTC
